# This workflow will install Python dependencies, run tests, and create a Code Coverage Report

name: Code Coverage

on:
  push:
    branches:
      - fall_2024
  pull_request:
    branches:
      - fall_2024

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Adjust to your Python version

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
          pip install pytest-cov

      - name: Run tests and generate coverage report
        run: |
          export PYTHONPATH=src
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
